added lock mechanism

diff --git a/bin/carrot b/bin/carrot
--- a/bin/carrot
+++ b/bin/carrot
@@ -1,18 +1,39 @@
 #!/bin/bash
 
-# a simple pomodoro app, to remind a developer 
+# a simple pomodoro app, to remind a developer
 # to rest his eyes and move his body
 
-trap 'small; stand=1' 8
-trap 'bigs' 14
+# reset to first break
+trap 'small; stand=1' SIGUSR1
+# reset to second break
+trap 'small; stand=2' SIGUSR2
+# reset to beginning
+trap 'big' SIGWINCH
+# print the timer
+trap 'log' SIGINFO
+# traps to be aliased in some dotfile
+# kill -x $(pgrep -f carrot)
 
+# remove lockdir before exiting
+trap 'loop=1; rm -rf "$lockdir"; exit' SIGTERM SIGHUP SIGINT SIGQUIT
+
+loop=0
 brake=0 
 stand=0
+
+braek() {
+	local minute=0
+	until (( minute == 60 )); do
+		sleep 1
+		minute=$(( minute+1 ))
+	done
+	brake=$(( brake+1 ))
+}
 
 small() {
 	osascript -e 'display notification "20 secs" with title "look away"'
     brake=0
-	stand=$(( $stand+1 )) 
+	stand=$(( stand+1 ))
 }
 
 big() {
@@ -21,24 +42,37 @@ big() {
 	brake=0
 }
 
-braek() {
-	local minute=0
-	until [ $minute -eq 60 ]; do
-		sleep 1
-		minute=$(( $minute+1 ))
-	done
-    brake=$(( $brake+1 ))
+log() {
+	osascript -e "display notification \"===============\" with title \"Break: $brake	Stand: $stand\""
 }
 
-while true; do         
-    if [ $brake -eq 20 ] && [ $stand -eq 2 ]; then
-		big
-	elif [ $brake -eq 20 ]; then             
-		small
-    else             
-		braek
-    fi  
-done
+main() {
+	while (( loop == 0 )); do         
+		if (( brake == 20 )) && (( stand == 2 ))
+		then
+			big
+		elif (( brake == 20 )); then             
+			small
+		else             
+			braek
+		fi  
+	done
+}
 
-# could alias 'kill -[8|14] [running pid]' to reset the stages
-# for windows cmder: msg.exe /time:4 $USERNAME "look away"
+# locking the script so that only
+# one instance can run at a time
+lockdir=/tmp/carrot.lock
+if mkdir "$lockdir" 2> /dev/null
+then
+	main	
+else
+    # echo "cannot acquire lock"
+    exit 1
+fi
+
+# for windows subsystem for linux 
+# could notify with powershell or:
+# msg.exe /time:4 $USERNAME "look away"
+# for ubuntu: notify-send
+# on linux could acquire lock with flock(1)
+
